// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8l_wwnpNR36QyOTlZ0TpuMugqxwGvJk',
    appId: '1:498343765035:web:2f79526b7f06d03737f66e',
    messagingSenderId: '498343765035',
    projectId: 'accounting-2fbdd',
    authDomain: 'accounting-2fbdd.firebaseapp.com',
    storageBucket: 'accounting-2fbdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcBpK1k1HCNVytAOg0Yf_IAb90Me6VsZM',
    appId: '1:498343765035:android:c308c05f335ae4bc37f66e',
    messagingSenderId: '498343765035',
    projectId: 'accounting-2fbdd',
    storageBucket: 'accounting-2fbdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYo_b8TpoRCZ4imcjH2hc6sIf9ZaQYEM',
    appId: '1:498343765035:ios:e9d7b50b6df78dd137f66e',
    messagingSenderId: '498343765035',
    projectId: 'accounting-2fbdd',
    storageBucket: 'accounting-2fbdd.appspot.com',
    iosBundleId: 'com.example.accounting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqYo_b8TpoRCZ4imcjH2hc6sIf9ZaQYEM',
    appId: '1:498343765035:ios:e9d7b50b6df78dd137f66e',
    messagingSenderId: '498343765035',
    projectId: 'accounting-2fbdd',
    storageBucket: 'accounting-2fbdd.appspot.com',
    iosBundleId: 'com.example.accounting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn8l_wwnpNR36QyOTlZ0TpuMugqxwGvJk',
    appId: '1:498343765035:web:1a203cdcbae462e337f66e',
    messagingSenderId: '498343765035',
    projectId: 'accounting-2fbdd',
    authDomain: 'accounting-2fbdd.firebaseapp.com',
    storageBucket: 'accounting-2fbdd.appspot.com',
  );
}
